# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 17:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('target_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freq.Client')),
            ],
            options={
                'ordering': ('priority', 'client'),
            },
        ),
        migrations.CreateModel(
            name='ProductArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='product_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='freq.ProductArea'),
        ),
        migrations.AlterUniqueTogether(
            name='featurerequest',
            unique_together=set([('client', 'priority')]),
        ),
    ]
